
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.io.*;
import javax.swing.*;
import static javax.swing.JOptionPane.showMessageDialog;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Luis Medina
 */
public class Analizar extends javax.swing.JFrame {

    /**
     * Creates new form Analizar
     */
    public Analizar() {
        initComponents();
        m = (DefaultTableModel) tblToken.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtEditor = new javax.swing.JTextArea();
        pnlArbol = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblToken = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        btnAnal = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuNwe = new javax.swing.JMenuItem();
        mnuGuardar = new javax.swing.JMenuItem();
        mnuAbrir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuAnal = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtEditor.setColumns(20);
        txtEditor.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtEditor.setRows(5);
        txtEditor.setText("total=precio+precio*0.16;");
        jScrollPane1.setViewportView(txtEditor);

        pnlArbol.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Arbol Sintactico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24))); // NOI18N

        javax.swing.GroupLayout pnlArbolLayout = new javax.swing.GroupLayout(pnlArbol);
        pnlArbol.setLayout(pnlArbolLayout);
        pnlArbolLayout.setHorizontalGroup(
            pnlArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlArbolLayout.setVerticalGroup(
            pnlArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        tblToken.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Token", "Tipo"
            }
        ));
        jScrollPane2.setViewportView(tblToken);
        if (tblToken.getColumnModel().getColumnCount() > 0) {
            tblToken.getColumnModel().getColumn(1).setResizable(false);
        }

        jToolBar1.setRollover(true);

        btnAnal.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnAnal.setText("Analizar");
        btnAnal.setFocusable(false);
        btnAnal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAnal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAnal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAnal);

        jMenu1.setText("File");

        mnuNwe.setText("Nuevo");
        jMenu1.add(mnuNwe);

        mnuGuardar.setText("Guardar");
        mnuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGuardarActionPerformed(evt);
            }
        });
        jMenu1.add(mnuGuardar);

        mnuAbrir.setText("Abrir");
        jMenu1.add(mnuAbrir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        mnuAnal.setText("Analizar");
        jMenuBar1.add(mnuAnal);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlArbol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(pnlArbol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGuardarActionPerformed
        String fileName;
        JFileChooser fc = new JFileChooser();
        fc.showSaveDialog(this);
        fileName = fc.getSelectedFile().getPath()+".txt";
        try {
            FileWriter fs = new FileWriter(fileName);
            fs.write(txtEditor.getText()); 
            fs.flush();
        } catch (IOException ex) {
            showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_mnuGuardarActionPerformed

    private void btnAnalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalActionPerformed
        analiza(txtEditor.getText());
    }//GEN-LAST:event_btnAnalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Analizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Analizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Analizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Analizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Analizar().setVisible(true);
            }
        });
    }
    
    public void analiza(String cad) {
        String pal = "";
        m.setRowCount(0);
        Object O[] = new Object[2];
        for (int i = 0; i < cad.length(); i++) {
            String car = cad.substring(i, i + 1);
            if (Grafo.esOP(car) == -1) {
                pal = pal + car;
            } else {
                if (Grafo.esIde(pal)) {
                    if (pal.length() > 1) {
                        O[0] = pal;
                        O[1] = "ide";
                        m.addRow(O);
                        O[0] = car;
                        O[1] = "op";
                        m.addRow(O);
                    }
                    pal = "";

                } else if (Grafo.esInt(pal)) {
                    if (pal.length() > 1) {
                        O[0] = pal;
                        O[1] = "int";
                        m.addRow(O);
                        O[0] = car;
                        O[1] = "op";
                        m.addRow(O);
                    }
                    pal = "";
                } else if (Grafo.esFloat(pal)) {
                    if (pal.length() > 1) {
                        O[0] = pal;
                        O[1] = "float";
                        m.addRow(O);
                        O[0] = car;
                        O[1] = "op";
                        m.addRow(O);
                    }
                    pal = "";
                }
            }
        }//for
    }
    
    private DefaultTableModel m;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mnuAbrir;
    private javax.swing.JMenu mnuAnal;
    private javax.swing.JMenuItem mnuGuardar;
    private javax.swing.JMenuItem mnuNwe;
    private javax.swing.JPanel pnlArbol;
    private javax.swing.JTable tblToken;
    private javax.swing.JTextArea txtEditor;
    // End of variables declaration//GEN-END:variables
}
