
import java.awt.event.KeyEvent;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DigitalMonster
 */
public class VColaDobleCompleta extends javax.swing.JFrame {

    /**
     * Creates new form VColaDobleCompleta
     */
    public VColaDobleCompleta() {
        initComponents();
         modelo=(DefaultTableModel)tblCD.getModel();
        txtTam.requestFocus();
    }

    private void limpiarTbl(){
        for(int i=0;i<tamTabla;i++){
            modelo.setValueAt(" ", 0, i);
            modelo.setValueAt(" ", 1, i);
            modelo.setValueAt(" ", 2, i);
        }
    }//LimpiarTabla
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCD = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btnDefinir = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        btnSacar = new javax.swing.JButton();
        btnSacarAll = new javax.swing.JButton();
        txtTam = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        txtNum = new javax.swing.JTextField();
        cmbOperaSalida = new javax.swing.JComboBox<>();
        txtInicio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        cmbOperaEntrada = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText(")");

        tblCD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblCD);

        jLabel6.setText("BUSCAR UN ELEMENTO");

        btnDefinir.setText("DEFINIR TAM");
        btnDefinir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDefinirActionPerformed(evt);
            }
        });

        btnIngresar.setText("INGRESAR DATO");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnSacar.setText("SACAR");
        btnSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacarActionPerformed(evt);
            }
        });

        btnSacarAll.setText("SACAR TODOS");
        btnSacarAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacarAllActionPerformed(evt);
            }
        });

        txtTam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTamActionPerformed(evt);
            }
        });
        txtTam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTamKeyTyped(evt);
            }
        });

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        cmbOperaSalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la ruta de salida", "Izquierda", "Derecha" }));
        cmbOperaSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbOperaSalidaMouseClicked(evt);
            }
        });
        cmbOperaSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOperaSalidaActionPerformed(evt);
            }
        });

        jLabel2.setText("POSICIONES DE LOS INDICES");

        txtFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFinActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("(");

        cmbOperaEntrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la ruta de Entrada", "Izquierda", "Derecha" }));
        cmbOperaEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbOperaEntradaMouseClicked(evt);
            }
        });
        cmbOperaEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOperaEntradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSacar)
                        .addGap(18, 18, 18)
                        .addComponent(btnSacarAll, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtTam, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnDefinir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnIngresar)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cmbOperaEntrada, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmbOperaSalida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(236, 236, 236)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtFin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnBuscar))))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE))
                        .addGap(48, 48, 48))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDefinir))
                        .addGap(16, 16, 16)
                        .addComponent(cmbOperaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIngresar))
                        .addGap(18, 18, 18)
                        .addComponent(cmbOperaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSacar)
                            .addComponent(btnSacarAll))))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDefinirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDefinirActionPerformed
        tam();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDefinirActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        try{
            limpiarTbl();
            cd.setOperaInsertar(cmbOperaEntrada.getSelectedItem().toString());
            cd.Insertar(Integer.parseInt(txtNum.getText()));
            txtInicio.setText(cd.getiFrente()+"");
            txtFin.setText(cd.getiFinal()+"");
            llenarTbl();
            //llenarTbl();
            txtNum.setText("");
        }
        catch(NumberFormatException e){
            llenarTbl();
            javax.swing.JOptionPane.showMessageDialog(this,e.getMessage());}
        // TODO add your handling code here:

        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarActionPerformed
        limpiarTbl();
        cd.setOperaRetirar(cmbOperaSalida.getSelectedItem().toString());
        cd.Retirar();
        txtInicio.setText(cd.getiFrente()+"");
        txtFin.setText(cd.getiFinal()+"");
        llenarTbl();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSacarActionPerformed

    private void btnSacarAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarAllActionPerformed
        limpiarTbl();
        cd.RetirarAll();
        txtInicio.setText(cd.getiFrente()+"");
        txtFin.setText(cd.getiFinal()+"");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSacarAllActionPerformed

    private void txtTamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTamKeyTyped
       char tecla=evt.getKeyChar();
        if(tecla==KeyEvent.VK_ENTER){
            btnDefinir.doClick();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtTamKeyTyped

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if(cd.buscar(Integer.parseInt(txtBuscar.getText()))){showMessageDialog(this,"Se encuentra ");}
        else{showMessageDialog(this,"No se encuntra ");}

        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cmbOperaSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbOperaSalidaMouseClicked
        cd.setOperaRetirar(cmbOperaSalida.getSelectedItem().toString());

        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOperaSalidaMouseClicked

    private void cmbOperaSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOperaSalidaActionPerformed
        cd.setOperaRetirar(cmbOperaSalida.toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOperaSalidaActionPerformed

    private void txtFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFinActionPerformed

    private void cmbOperaEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbOperaEntradaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOperaEntradaMouseClicked

    private void cmbOperaEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOperaEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOperaEntradaActionPerformed

    private void txtTamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTamActionPerformed

    private void tam(){
    try{
        tamTabla=Integer.parseInt(txtTam.getText());
        cd=new ColaDobleCompleta(tamTabla);
        modelo.setColumnCount(tamTabla);
        modelo.setRowCount(3);
    }
    catch(NumberFormatException e){
        javax.swing.JOptionPane.showMessageDialog(this,e.getMessage());
    }catch(ArrayIndexOutOfBoundsException e){}
    }//Insertar Tamaño de la cola
    
     private void llenarTbl(){
        for(int i=0;i<(tamTabla);i++){
            modelo.setValueAt(cd.mostrar()[i], 0, i);
            modelo.setValueAt("Final", 1, cd.getiFinal());
            modelo.setValueAt("Frente", 2, cd.getiFrente());            
        }
    }//LLenar tabla 
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VColaDobleCompleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VColaDobleCompleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VColaDobleCompleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VColaDobleCompleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VColaDobleCompleta().setVisible(true);
            }
        });
    }
 public ColaDobleCompleta cd;
    private int tamTabla;
    private DefaultTableModel modelo;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDefinir;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnSacar;
    private javax.swing.JButton btnSacarAll;
    private javax.swing.JComboBox<String> cmbOperaEntrada;
    private javax.swing.JComboBox<String> cmbOperaSalida;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCD;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtFin;
    private javax.swing.JTextField txtInicio;
    private javax.swing.JTextField txtNum;
    private javax.swing.JTextField txtTam;
    // End of variables declaration//GEN-END:variables
}
