
import java.awt.event.KeyEvent;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usuario
 */
public class VICola extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public VICola() {
        initComponents();
        modelo=(DefaultTableModel)tblCola.getModel();
        txtTam.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCola = new javax.swing.JTable();
        btnSacar = new javax.swing.JButton();
        txtLocalizar = new javax.swing.JTextField();
        btnTam = new javax.swing.JButton();
        txtTam = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNum = new javax.swing.JTextField();
        btnNums = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        tblCola.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblCola.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblCola);

        btnSacar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSacar.setText("Sacar");
        btnSacar.setEnabled(false);
        btnSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacarActionPerformed(evt);
            }
        });

        txtLocalizar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnTam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTam.setText("Aceptar");
        btnTam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTamActionPerformed(evt);
            }
        });

        txtTam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTamKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Tamaño");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Numero");

        txtNum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumKeyTyped(evt);
            }
        });

        btnNums.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNums.setText("Insertar");
        btnNums.setEnabled(false);
        btnNums.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumsActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\DigitalMonster\\Documents\\TEC de TEPIC\\SEMESTRE 3\\Estructuras de Datos\\Unidad 2\\Pila\\Imagenes\\btn.png")); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtTam, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtLocalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNums)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSacar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtTam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtLocalizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTam))
                    .addComponent(jLabel2))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNums)
                    .addComponent(btnSacar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarActionPerformed
        limiarTblV2();
        c.salida();
        llenarTblV2();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSacarActionPerformed
    private void tam(){
        try{
            tamTabla=Integer.parseInt(txtTam.getText());
            c=new ColaSimple(tamTabla);
            modelo.setColumnCount(2);
            modelo.setRowCount(tamTabla);
        }
        catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(this,e.getMessage());
        }catch(ArrayIndexOutOfBoundsException e){}
    }//para el tamaño 
    private void llenarTblV2(){
        for(int i=0;i<=c.getTope();i++){
            modelo.setValueAt(c.mostrar()[i], i, 0);
            if(c.getTope()!=0)
                modelo.setValueAt(" ", c.getTope()-1, 1);        
            modelo.setValueAt("<---", c.getTope(), 1);
            if(!c.llena())
                modelo.setValueAt(" ", c.getTope()+1, 1);
           
        }
        if(c.vacia())
            modelo.setValueAt(" ", 0, 1);
    }
     public void limiarTblV2(){
          for(int i=0;i<=c.getTope();i++){
            modelo.setValueAt(" ", i, 0);
        }
    }
    private void btnTamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTamActionPerformed
        tam();
        txtNum.requestFocus();
        btnNums.setEnabled(true);
        btnSacar.setEnabled(true);

    }//GEN-LAST:event_btnTamActionPerformed

    private void txtTamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTamKeyTyped
        char tecla=evt.getKeyChar();
        if(tecla==KeyEvent.VK_ENTER){
            btnTam.doClick();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTamKeyTyped

    private void txtNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumKeyTyped
        char tecla=evt.getKeyChar();
        if(tecla==KeyEvent.VK_ENTER){
            btnNums.doClick();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumKeyTyped

    private void btnNumsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumsActionPerformed
        try{

            c.entrada(Integer.parseInt(txtNum.getText()));
            //llenarTbl();
            llenarTblV2();
            txtNum.setText("");
        }
        catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(this,e.getMessage());}
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNumsActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
      if(c.existe(Integer.parseInt(txtLocalizar.getText()))) showMessageDialog(null,"si esta en la pila");
        else  showMessageDialog(null,"no esta en la cola");
        txtLocalizar.requestFocus();
        txtLocalizar.setText("");
        // TODO add your handling code here:

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked
      private int tamTabla;
    private DefaultTableModel modelo;
    public ColaSimple c;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNums;
    private javax.swing.JButton btnSacar;
    private javax.swing.JButton btnTam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCola;
    private javax.swing.JTextField txtLocalizar;
    private javax.swing.JTextField txtNum;
    private javax.swing.JTextField txtTam;
    // End of variables declaration//GEN-END:variables
}
