
import java.awt.event.KeyEvent;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usuario
 */
public class VIPila extends javax.swing.JInternalFrame {

    /**
     * Creates new form VIPila
     */
    public VIPila() {
        initComponents();
        modelo=(DefaultTableModel)tblPila.getModel();
        
        txtTam.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTam = new javax.swing.JTextField();
        btnTam = new javax.swing.JButton();
        txtLocalizar = new javax.swing.JTextField();
        btnLocalizar = new javax.swing.JButton();
        btnSacar = new javax.swing.JButton();
        btnNums = new javax.swing.JButton();
        txtNum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPila = new javax.swing.JTable();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Tamaño");

        txtTam.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtTam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTamKeyTyped(evt);
            }
        });

        btnTam.setText("Aceptar");
        btnTam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTamActionPerformed(evt);
            }
        });

        txtLocalizar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtLocalizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLocalizarKeyTyped(evt);
            }
        });

        btnLocalizar.setText("Localizar");
        btnLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalizarActionPerformed(evt);
            }
        });

        btnSacar.setText("Sacar");
        btnSacar.setEnabled(false);
        btnSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacarActionPerformed(evt);
            }
        });

        btnNums.setText("Ingresar");
        btnNums.setEnabled(false);
        btnNums.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumsActionPerformed(evt);
            }
        });

        txtNum.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Numero");

        tblPila.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblPila.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tblPila.setForeground(new java.awt.Color(255, 0, 0));
        tblPila.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblPila.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblPila.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jScrollPane1.setViewportView(tblPila);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnNums))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTam, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtLocalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSacar, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(btnLocalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTam, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLocalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLocalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNums, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSacar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void tam(){
    try{
        tamTabla=Integer.parseInt(txtTam.getText());
        p=new Pila(tamTabla);
        modelo.setColumnCount(2);
        modelo.setRowCount(tamTabla);
    }
    catch(NumberFormatException e){
        javax.swing.JOptionPane.showMessageDialog(this,e.getMessage());
    }catch(ArrayIndexOutOfBoundsException e){}
    }//para el tamaño
    private void llenarTbl(){ 
        for(int i=0;i<=p.getTope();i++){
            System.out.println("tope"+p.getTope()+"   i"+i);
            modelo.setValueAt(p.mostrar()[i], p.getTope(), 0);
            if(p.getTope()!=0)
                modelo.setValueAt(" ", p.getTope()-1, 1);        
            modelo.setValueAt("<---", p.getTope(), 1);        
        }
    }//Llenar tabla con la pila
    private void llenarTblV2(){
        for(int i=0;i<=p.getTope();i++){
            modelo.setValueAt(p.mostrar()[i], i, 0);
            if(p.getTope()!=0)
                modelo.setValueAt(" ", p.getTope()-1, 1);        
            modelo.setValueAt("<---", p.getTope(), 1);
            if(!p.llena())
                modelo.setValueAt(" ", p.getTope()+1, 1);
           
        }
        if(p.vacia())
            modelo.setValueAt(" ", 0, 1);
    }

    public void limiarTblV2(){
          for(int i=0;i<=p.getTope();i++){
            modelo.setValueAt(" ", i, 0);
        }
    }    
    private void txtTamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTamKeyTyped
        char tecla=evt.getKeyChar();
        if(tecla==KeyEvent.VK_ENTER){
            btnTam.doClick();
        }
    }//GEN-LAST:event_txtTamKeyTyped

    private void btnTamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTamActionPerformed
        tam();
        txtNum.requestFocus();
        btnNums.setEnabled(true);
        btnSacar.setEnabled(true);
    }//GEN-LAST:event_btnTamActionPerformed

    private void txtLocalizarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLocalizarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocalizarKeyTyped

    private void btnLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalizarActionPerformed
        if(p.existe(Integer.parseInt(txtLocalizar.getText()))) showMessageDialog(null,"si esta en la pila");
        else  showMessageDialog(null,"no esta en la pila");
        txtLocalizar.requestFocus();
        txtLocalizar.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLocalizarActionPerformed

    private void btnSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarActionPerformed
        limiarTblV2();
        p.sacar();
        llenarTblV2();
    }//GEN-LAST:event_btnSacarActionPerformed

    private void btnNumsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumsActionPerformed
        try{

            p.meter(Integer.parseInt(txtNum.getText()));
            //llenarTbl();
            llenarTblV2();
            txtNum.setText("");
        }
        catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(this,e.getMessage());}
    }//GEN-LAST:event_btnNumsActionPerformed

    private void txtNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumKeyTyped
        char tecla=evt.getKeyChar();
        if(tecla==KeyEvent.VK_ENTER){
            btnNums.doClick();
        }
    }//GEN-LAST:event_txtNumKeyTyped
    private int tamTabla;
    public Pila p;

    private DefaultTableModel modelo;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLocalizar;
    private javax.swing.JButton btnNums;
    private javax.swing.JButton btnSacar;
    private javax.swing.JButton btnTam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPila;
    private javax.swing.JTextField txtLocalizar;
    private javax.swing.JTextField txtNum;
    private javax.swing.JTextField txtTam;
    // End of variables declaration//GEN-END:variables
}
