/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package directa;

import AppPackage.AnimationClass;
import java.awt.FileDialog;
import java.awt.Frame;
import java.awt.Image;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.EOFException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Marval
 */
public class ventanaDirecta extends javax.swing.JFrame {
    ArrayList<Integer> numerosOrdenarD = new ArrayList<Integer>();
     ArrayList<Integer> numerosOrdenarN = new ArrayList<Integer>();
    
    private String lista;

    /**
     * Creates new form ventanaDirecta
     */
    public ventanaDirecta() {
        initComponents();
        //   "/directa/5fd67606-8862-479a-8458-f15f8e7502562.png"


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnThis2 = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnVerArray = new javax.swing.JButton();
        btnOrdenar = new javax.swing.JButton();
        lblNumeros = new javax.swing.JLabel();
        lblIntroducirNumeros = new javax.swing.JLabel();
        txtIntroducirNumeros = new javax.swing.JTextField();
        txtNumerosOrdenados = new javax.swing.JTextField();
        txtNumeros = new javax.swing.JTextField();
        lblIntroducirNumeros1 = new javax.swing.JLabel();
        lblNumeros1 = new javax.swing.JLabel();
        btnAgregar1 = new javax.swing.JButton();
        btnAbrir1 = new javax.swing.JButton();
        btnGuardar1 = new javax.swing.JButton();
        btnNuevo1 = new javax.swing.JButton();
        btnVerArray1 = new javax.swing.JButton();
        btnOrdenar1 = new javax.swing.JButton();
        txtNumeros1 = new javax.swing.JTextField();
        txtIntroducirNumeros1 = new javax.swing.JTextField();
        txtNumerosOrdenados1 = new javax.swing.JTextField();
        lblajolotito = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mezcla Directa");
        setMaximumSize(new java.awt.Dimension(595, 460));
        setMinimumSize(new java.awt.Dimension(595, 460));
        setPreferredSize(new java.awt.Dimension(595, 460));
        setResizable(false);
        setSize(new java.awt.Dimension(595, 500));
        getContentPane().setLayout(null);

        btnThis2.setBackground(new java.awt.Color(255, 153, 0));
        btnThis2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/directa/Sun-icon.png"))); // NOI18N
        btnThis2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThis2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnThis2);
        btnThis2.setBounds(560, 270, 30, 60);

        btnAgregar.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(180, 170, 79, 23);

        btnAbrir.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btnAbrir.setText("Abrir");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });
        getContentPane().add(btnAbrir);
        btnAbrir.setBounds(260, 170, 60, 23);

        btnGuardar.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(320, 170, 79, 23);

        btnNuevo.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo);
        btnNuevo.setBounds(400, 170, 71, 23);

        btnVerArray.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btnVerArray.setText("ver Array");
        btnVerArray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerArrayActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerArray);
        btnVerArray.setBounds(470, 170, 82, 23);

        btnOrdenar.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btnOrdenar.setText("Ordenar");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });
        getContentPane().add(btnOrdenar);
        btnOrdenar.setBounds(470, 210, 82, 60);

        lblNumeros.setBackground(new java.awt.Color(204, 153, 0));
        lblNumeros.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        lblNumeros.setText("Datos Ordenados");
        lblNumeros.setOpaque(true);
        getContentPane().add(lblNumeros);
        lblNumeros.setBounds(20, 310, 140, 20);

        lblIntroducirNumeros.setBackground(new java.awt.Color(204, 153, 0));
        lblIntroducirNumeros.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        lblIntroducirNumeros.setText("Datos a Ordenar - Mezcla Directa");
        lblIntroducirNumeros.setOpaque(true);
        getContentPane().add(lblIntroducirNumeros);
        lblIntroducirNumeros.setBounds(20, 150, 260, 20);

        txtIntroducirNumeros.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        txtIntroducirNumeros.setText("Introduzca un número");
        txtIntroducirNumeros.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIntroducirNumerosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIntroducirNumerosFocusLost(evt);
            }
        });
        getContentPane().add(txtIntroducirNumeros);
        txtIntroducirNumeros.setBounds(20, 170, 150, 30);

        txtNumerosOrdenados.setEditable(false);
        getContentPane().add(txtNumerosOrdenados);
        txtNumerosOrdenados.setBounds(20, 330, 530, 100);

        txtNumeros.setEditable(false);
        txtNumeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumerosActionPerformed(evt);
            }
        });
        getContentPane().add(txtNumeros);
        txtNumeros.setBounds(20, 210, 450, 60);

        lblIntroducirNumeros1.setBackground(new java.awt.Color(204, 153, 0));
        lblIntroducirNumeros1.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        lblIntroducirNumeros1.setText("Datos a Ordenar - Mezcla Natural");
        lblIntroducirNumeros1.setOpaque(true);
        getContentPane().add(lblIntroducirNumeros1);
        lblIntroducirNumeros1.setBounds(650, 150, 260, 20);

        lblNumeros1.setBackground(new java.awt.Color(204, 153, 0));
        lblNumeros1.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        lblNumeros1.setText("Datos Ordenados");
        lblNumeros1.setOpaque(true);
        getContentPane().add(lblNumeros1);
        lblNumeros1.setBounds(650, 310, 140, 20);

        btnAgregar1.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btnAgregar1.setText("Agregar");
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar1);
        btnAgregar1.setBounds(810, 170, 79, 23);

        btnAbrir1.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btnAbrir1.setText("Abrir");
        btnAbrir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrir1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAbrir1);
        btnAbrir1.setBounds(890, 170, 59, 23);

        btnGuardar1.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btnGuardar1.setText("Guardar");
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar1);
        btnGuardar1.setBounds(950, 170, 79, 23);

        btnNuevo1.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btnNuevo1.setText("Nuevo");
        btnNuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevo1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo1);
        btnNuevo1.setBounds(1030, 170, 71, 23);

        btnVerArray1.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btnVerArray1.setText("ver Array");
        btnVerArray1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerArray1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerArray1);
        btnVerArray1.setBounds(1100, 170, 82, 23);

        btnOrdenar1.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btnOrdenar1.setText("Ordenar");
        btnOrdenar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnOrdenar1);
        btnOrdenar1.setBounds(1100, 210, 82, 60);

        txtNumeros1.setEditable(false);
        getContentPane().add(txtNumeros1);
        txtNumeros1.setBounds(650, 210, 450, 60);

        txtIntroducirNumeros1.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        txtIntroducirNumeros1.setText("Introduzca un número");
        txtIntroducirNumeros1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIntroducirNumeros1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIntroducirNumeros1FocusLost(evt);
            }
        });
        getContentPane().add(txtIntroducirNumeros1);
        txtIntroducirNumeros1.setBounds(650, 170, 150, 30);

        txtNumerosOrdenados1.setEditable(false);
        getContentPane().add(txtNumerosOrdenados1);
        txtNumerosOrdenados1.setBounds(650, 330, 530, 100);

        lblajolotito.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        lblajolotito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/directa/5fd67606-8862-479a-8458-f15f8e7502562.png"))); // NOI18N
        lblajolotito.setToolTipText("");
        lblajolotito.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblajolotito.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblajolotito);
        lblajolotito.setBounds(280, 40, 220, 130);

        jLabel1.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jLabel1.setText("Eoneo Software");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 130, 40);

        lblFondo.setBackground(new java.awt.Color(255, 153, 0));
        lblFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/directa/fondo 2.1.png"))); // NOI18N
        getContentPane().add(lblFondo);
        lblFondo.setBounds(-150, 0, 850, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThis2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThis2ActionPerformed
        animacioncontenedores();
    }//GEN-LAST:event_btnThis2ActionPerformed

    private void animacioncontenedores(){
        AnimationClass d = new AnimationClass();//Directa
        AnimationClass d1 = new AnimationClass();
        AnimationClass d2 = new AnimationClass();
        AnimationClass d3 = new AnimationClass();
        AnimationClass d4 = new AnimationClass();
        AnimationClass d5 = new AnimationClass();
        AnimationClass d6 = new AnimationClass();
        AnimationClass d7 = new AnimationClass();
        AnimationClass d8 = new AnimationClass();
        AnimationClass d9 = new AnimationClass();
        AnimationClass d10 = new AnimationClass();
        AnimationClass d11 = new AnimationClass();
        AnimationClass d12 = new AnimationClass();
        AnimationClass d13 = new AnimationClass();
        AnimationClass d14 = new AnimationClass();
        AnimationClass d15 = new AnimationClass();
        AnimationClass d16 = new AnimationClass();
        AnimationClass d17 = new AnimationClass();
        AnimationClass d18 = new AnimationClass();
        AnimationClass d19 = new AnimationClass();
        AnimationClass d20 = new AnimationClass();
        AnimationClass d21 = new AnimationClass();
        AnimationClass d22 = new AnimationClass();
        AnimationClass d23 = new AnimationClass();
        AnimationClass d24 = new AnimationClass();
        AnimationClass d25 = new AnimationClass();
        
        AnimationClass f = new AnimationClass();//Natural
        AnimationClass f1 = new AnimationClass();
        AnimationClass f2 = new AnimationClass();
        AnimationClass f3 = new AnimationClass();
        AnimationClass f4 = new AnimationClass();
        AnimationClass f5 = new AnimationClass();
        AnimationClass f6 = new AnimationClass();
        AnimationClass f7 = new AnimationClass();
        AnimationClass f8 = new AnimationClass();
        AnimationClass f9 = new AnimationClass();
        AnimationClass f10 = new AnimationClass();
        AnimationClass f11 = new AnimationClass();
        AnimationClass f12 = new AnimationClass();
        AnimationClass f13 = new AnimationClass();
        AnimationClass f14 = new AnimationClass();
        AnimationClass f15 = new AnimationClass();
        AnimationClass f16 = new AnimationClass();
        AnimationClass f17 = new AnimationClass();
        AnimationClass f18 = new AnimationClass();
        AnimationClass f19 = new AnimationClass();
        AnimationClass f20 = new AnimationClass();
        AnimationClass f21 = new AnimationClass();
        AnimationClass f22 = new AnimationClass();
        AnimationClass f23 = new AnimationClass();
        AnimationClass f24 = new AnimationClass();
        AnimationClass f25 = new AnimationClass();
        //----------------------------------MEZCLA DIRECTA-DER----------------------------------------------//
            //Labels-------------
        d.jLabelXRight(20, 650, 40, 10, lblIntroducirNumeros);
        d1.jLabelXRight(20, 650, 40, 10, lblNumeros);
        //d2.jLabelXRight(20, 650, 40, 10, lblProcedimiento);
            //Botones----------
        d3.jButtonXRight(180, 810, 40, 10, btnAgregar);
        d4.jButtonXRight(260, 890, 40, 10, btnAbrir);
        d5.jButtonXRight(320, 950, 40, 10, btnGuardar);
        d6.jButtonXRight(400, 1030, 40, 10, btnNuevo);
        d7.jButtonXRight(470, 1100, 40, 10, btnVerArray);
        d8.jButtonXRight(470, 1100, 40, 10, btnOrdenar);
            //Textos-------------
         d9.jTextFieldXRight(20,650, 40,10, txtIntroducirNumeros);
         d10.jTextFieldXRight(20,650, 40,10, txtNumeros);
         d11.jTextFieldXRight(20,650, 40,10, txtNumerosOrdenados);
         //d12.jTextFieldXRight(20,650, 40,10, txtProcedimiento);
         
        //_---------------------------------------------------------------------------------------------------------//
          //----------------------------------MEZCLA DIRECTA-IZQ----------------------------------------------//
            //Labels-------------
        d13.jLabelXLeft(650, 20, 40, 10, lblIntroducirNumeros);
        d14.jLabelXLeft(650, 20, 40, 10, lblNumeros);
        //d15.jLabelXLeft(650, 20, 40, 10, lblProcedimiento);
            //Botones----------
        d16.jButtonXLeft(810, 180, 40, 10, btnAgregar);
        d17.jButtonXLeft(890, 8260, 40, 10, btnAbrir);
        d18.jButtonXLeft(950, 320, 40, 10, btnGuardar);
        d19.jButtonXLeft(1030, 400, 40, 10, btnNuevo);
        d20.jButtonXLeft(1100, 470, 40, 10, btnVerArray);
        d21.jButtonXLeft(1100, 470, 40, 10, btnOrdenar);
            //Textos-------------
         d22.jTextFieldXLeft(650,20, 40,10, txtIntroducirNumeros);
         d23.jTextFieldXLeft(650,20, 40,10, txtNumeros);
         d24.jTextFieldXLeft(650,20, 40,10, txtNumerosOrdenados);
         //d25.jTextFieldXLeft(650,20, 40,10, txtProcedimiento);
        
        //_---------------------------------------------------------------------------------------------------------//
        //---------------------------------------LABEL FONDO---------------------------------------------//
        AnimationClass lbl = new AnimationClass();
        AnimationClass lbl2 = new AnimationClass();
       lbl.jLabelXRight(-150, 0, 40, 2, lblFondo);
       lbl2.jLabelXLeft(0, -150, 40, 2, lblFondo);
        
        //----------------------------------MEZCLA NATURAL-IZQ----------------------------------------------//
            //Labels-------------
        f13.jLabelXLeft(650, 20, 40, 10, lblIntroducirNumeros1);
        f14.jLabelXLeft(650, 20, 40, 10, lblNumeros1);
        //f15.jLabelXLeft(650, 20, 40, 10, lblProcedimiento1);
            //Botones----------
        f16.jButtonXLeft(810, 180, 40, 10, btnAgregar1);
        f17.jButtonXLeft(890, 260, 40, 10, btnAbrir1);
        f18.jButtonXLeft(950, 320, 40, 10, btnGuardar1);
        f19.jButtonXLeft(1030, 400, 40, 10, btnNuevo1);
        f20.jButtonXLeft(1100, 470, 40, 10, btnVerArray1);
        f21.jButtonXLeft(1100, 470, 40, 10, btnOrdenar1);
            //Textos-------------
         f22.jTextFieldXLeft(650,20, 40,10, txtIntroducirNumeros1);
         f23.jTextFieldXLeft(650,20, 40,10, txtNumeros1);
         f24.jTextFieldXLeft(650,20, 40,10, txtNumerosOrdenados1);
         //f25.jTextFieldXLeft(650,20, 40,10, txtProcedimiento1);

        //_---------------------------------------------------------------------------------------------------------//
                //----------------------------------MEZCLA NATURAL-DER----------------------------------------------//
            //Labels-------------
        f.jLabelXRight(20, 650, 40, 10, lblIntroducirNumeros1);
        f1.jLabelXRight(20, 650, 40, 10, lblNumeros1);
       // f2.jLabelXRight(20, 650, 40, 10, lblProcedimiento1);
            //Botones----------
        f3.jButtonXRight(180, 810, 40, 10, btnAgregar1);
        f4.jButtonXRight(260, 890, 40, 10, btnAbrir1);
        f5.jButtonXRight(320, 950, 40, 10, btnGuardar1);
        f6.jButtonXRight(400, 1030, 40, 10, btnNuevo1);
        f7.jButtonXRight(470, 1100, 40, 10, btnVerArray1);
        f8.jButtonXRight(470, 1100, 40, 10, btnOrdenar1);
            //Textos-------------
         f9.jTextFieldXRight(20,650, 40,10, txtIntroducirNumeros1);
         f10.jTextFieldXRight(20,650, 40,10, txtNumeros1);
         f11.jTextFieldXRight(20,650, 40,10, txtNumerosOrdenados1);
        // f12.jTextFieldXRight(20,650, 40,10, txtProcedimiento1);
        
        //_---------------------------------------------------------------------------------------------------------//
    }
    private void btnVerArrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerArrayActionPerformed
        showMessageDialog(this,"Arreglo de enteros: "+numerosOrdenarD.toString());
    }//GEN-LAST:event_btnVerArrayActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
       try{
            //txtProcedimiento.setText(null);
            txtNumerosOrdenados.setText(null);
            int arreglo[] = new int[numerosOrdenarD.size()];
            for(int i=0; i<numerosOrdenarD.size();i++){
                arreglo[i]=numerosOrdenarD.get(i);
            }
            mezcla_directa(arreglo);
            String cad="";
            for(int j=0;j<arreglo.length;j++){
                cad=cad+" [ "+arreglo[j]+" ] ";
            }
            txtNumerosOrdenados.setText(cad);
       }catch(Exception ex){
           showMessageDialog(this,"whoops, ese no es un número. >:T      "+ex.getMessage());
           Logger.getLogger(ventanaDirecta.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_btnOrdenarActionPerformed
    
    public static int[] mezcla_directa(int[] array) {
      if (array.length > 1) {
         int i,j,k;
         int ElmIzq = array.length / 2, ElmDer = array.length - ElmIzq;
         int ArrIzq[] = new int[ElmIzq], ArrDer[] = new int[ElmDer];
         for (i = 0; i < ElmIzq; i++)
            ArrIzq[i] = array[i];
         for (i = ElmIzq; i < ElmIzq + ElmDer; i++)
            ArrDer[i-ElmIzq] = array[i];
         ArrIzq = mezcla_directa(ArrIzq);

         ArrDer = mezcla_directa(ArrDer);

         i=0;j=k=0;
         while(ArrIzq.length != j && ArrDer.length !=k)
            if(ArrIzq[j]<ArrDer[k]) array[i++] = ArrIzq[j++];
            else array[i++] = ArrDer[k++];
         while(ArrIzq.length != j) array[i++] = ArrIzq[j++];
         while(ArrDer.length != k) array[i++] = ArrDer[k++];

      }
        return array;

        
    }
    
    public static void mezcla_natural(int[] array){
        int Izquierda, izq=0, Derecha =array.length-1, der=Derecha;
        boolean ordenado;
        do{
            ordenado = true;
            Izquierda =0;
            while(Izquierda < Derecha){
                izq = Izquierda;
                while(izq<Derecha && array[izq] <=array[izq+1]) izq++;
                der=izq+1;
                while(der == Derecha-1 || der < Derecha && array[der]<=array[der+1]) der++;
                if(der<=Derecha) {
                    mezcla_directa(array);
                    ordenado=false;
                }
                Izquierda = izq;
            }
        }while(!ordenado);
        
    }
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String array="";
        for(int i=0;i<numerosOrdenarD.size();i++){
            array = array+numerosOrdenarD.get(i).toString()+", ";
        }
        numero n = new numero();
        n.guardar(array);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        txtNumeros.setText("");
       // txtProcedimiento.setText("");
        numerosOrdenarD.clear();
        txtNumerosOrdenados.setText("");
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        String nombre;
        FileDialog selec = new FileDialog(this, "Elija el archivo que desea abrir", FileDialog.LOAD);
        selec.setVisible(true);
        if (selec.getFile() != null) {
            nombre = selec.getDirectory() + selec.getFile();
            setTitle(nombre);
            try {
                FileInputStream fb = new FileInputStream(nombre);
                DataInputStream fdr = new DataInputStream(fb);
                String i2,i3,txtcad="";
                int number=0;
                while (fdr != null) {
                    if(fdr.readChar()!=','){
                        i2 = fdr.readLine();
                        i3 = i2.replaceAll("\\s", "");
                        String[] parts = i3.split(",");
                        for(int i=0;i<parts.length;i++){
                            number = Integer.parseInt(parts[i]);
                            numerosOrdenarD.add(number);
                            txtcad = txtcad +" [ "+ number + " ] ";
                            
                        }
                        //showMessageDialog(this, i2);
                        txtNumeros.setText(txtcad);
                        
                        //numerosOrdenarD.add(Integer.parseInt(i2));
                    }
                }

            } catch (EOFException ex) {
                Logger.getLogger(ventanaDirecta.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("¡¡TODO ESTÁ BIEN!!, SE ESTABILIZARÁ.\n OTTO, yyz");
                
            } catch (FileNotFoundException ex) {
                Logger.getLogger(ventanaDirecta.class.getName()).log(Level.SEVERE, null, ex);
                
            } catch (IOException ex) {
                showMessageDialog(null, "Archivo no valido");
                setTitle("");
            }

    }
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
     int numero;
        try{
            numero = Integer.parseInt(txtIntroducirNumeros.getText());
           numerosOrdenarD.add(numero);           
           txtNumeros.setText(txtNumeros.getText()+numero+", ");
           txtIntroducirNumeros.setText("");
           txtIntroducirNumeros.requestFocus();
           
       }catch(NumberFormatException r){
           JOptionPane.showMessageDialog(this, "Error... Número Erróneo ");
       }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtIntroducirNumerosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIntroducirNumerosFocusLost
        if (txtIntroducirNumeros.getText().equals("")) {
            txtIntroducirNumeros.setText("Introduzca un número");
        } 
    }//GEN-LAST:event_txtIntroducirNumerosFocusLost

    private void txtIntroducirNumerosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIntroducirNumerosFocusGained
        if (txtIntroducirNumeros.getText().equals("Introduzca un número")) {
            txtIntroducirNumeros.setText("");
        }        
    }//GEN-LAST:event_txtIntroducirNumerosFocusGained

    private void txtIntroducirNumeros1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIntroducirNumeros1FocusGained
         if (txtIntroducirNumeros1.getText().equals("Introduzca un número")) {
            txtIntroducirNumeros1.setText("");
        } 
    }//GEN-LAST:event_txtIntroducirNumeros1FocusGained

    private void txtIntroducirNumeros1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIntroducirNumeros1FocusLost
         if (txtIntroducirNumeros1.getText().equals("")) {
            txtIntroducirNumeros1.setText("Introduzca un número");
        } 
    }//GEN-LAST:event_txtIntroducirNumeros1FocusLost

    private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar1ActionPerformed
        
             int numero;
        try{
            numero = Integer.parseInt(txtIntroducirNumeros1.getText());
           numerosOrdenarN.add(numero);           
           txtNumeros1.setText(txtNumeros1.getText()+numero+", ");
           txtIntroducirNumeros1.setText("");
           txtIntroducirNumeros1.requestFocus();
           
       }catch(NumberFormatException r){
           JOptionPane.showMessageDialog(this, "Error... Número Erróneo ");
       }
        
    }//GEN-LAST:event_btnAgregar1ActionPerformed

    private void btnAbrir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrir1ActionPerformed
        
                String nombre;
        FileDialog selec = new FileDialog(this, "Elija el archivo que desea abrir", FileDialog.LOAD);
        selec.setVisible(true);
        if (selec.getFile() != null) {
            nombre = selec.getDirectory() + selec.getFile();
            setTitle(nombre);
            try {
                FileInputStream fb = new FileInputStream(nombre);
                DataInputStream fdr = new DataInputStream(fb);
                String i2,i3;
                int number=0;
                while (fdr != null) {
                    if(fdr.readChar()!=','){
                        i2 = fdr.readLine();
                        i3 = i2.replaceAll("\\s", "");
                        String[] parts = i3.split(",");
                        for(int i=0;i<parts.length;i++){
                            number = Integer.parseInt(parts[i]);
                            numerosOrdenarN.add(number);
                        }
                        //showMessageDialog(this, i2);
                        
                        
                        //numerosOrdenarD.add(Integer.parseInt(i2));
                    }
                }

            } catch (EOFException ex) {
                Logger.getLogger(ventanaDirecta.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("¡¡TODO ESTÁ BIEN!!, SE ESTABILIZARÁ.\n OTTO, yyz");
                
            } catch (FileNotFoundException ex) {
                Logger.getLogger(ventanaDirecta.class.getName()).log(Level.SEVERE, null, ex);
                
            } catch (IOException ex) {
                showMessageDialog(null, "Archivo no valido");
                setTitle("");
            }

    }
        
    }//GEN-LAST:event_btnAbrir1ActionPerformed

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
                String array="";
        for(int i=0;i<numerosOrdenarN.size();i++){
            array = array+numerosOrdenarN.get(i).toString()+", ";
        }
        numero n = new numero();
        n.guardar(array);
    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void btnNuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevo1ActionPerformed
         txtNumeros1.setText("");
        //txtProcedimiento1.setText("");
        numerosOrdenarN.clear();
        txtNumerosOrdenados1.setText("");
    }//GEN-LAST:event_btnNuevo1ActionPerformed

    private void btnVerArray1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerArray1ActionPerformed
        showMessageDialog(this,"Arreglo de enteros: "+numerosOrdenarN.toString());
    }//GEN-LAST:event_btnVerArray1ActionPerformed

    private void btnOrdenar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenar1ActionPerformed
              try{
            //txtProcedimiento.setText(null);
            txtNumerosOrdenados1.setText(null);
            int arreglo[] = new int[numerosOrdenarN.size()];
            for(int i=0; i<numerosOrdenarN.size();i++){
                arreglo[i]=numerosOrdenarN.get(i);
            }
            mezcla_natural(arreglo);
            String cad="";
            for(int j=0;j<arreglo.length;j++){
                cad=cad+" [ "+arreglo[j]+" ] ";
            }
            txtNumerosOrdenados1.setText(cad);
       }catch(Exception ex){
           showMessageDialog(this,"whoops, ese no es un número. >:T      "+ex.getMessage());
           Logger.getLogger(ventanaDirecta.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_btnOrdenar1ActionPerformed

    private void txtNumerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumerosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumerosActionPerformed


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaDirecta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaDirecta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaDirecta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaDirecta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ventanaDirecta().setVisible(true);
            }
        });
    }
    private int A[];
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnAbrir1;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnNuevo1;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JButton btnOrdenar1;
    private javax.swing.JButton btnThis2;
    private javax.swing.JButton btnVerArray;
    private javax.swing.JButton btnVerArray1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblIntroducirNumeros;
    private javax.swing.JLabel lblIntroducirNumeros1;
    private javax.swing.JLabel lblNumeros;
    private javax.swing.JLabel lblNumeros1;
    private javax.swing.JLabel lblajolotito;
    private javax.swing.JTextField txtIntroducirNumeros;
    private javax.swing.JTextField txtIntroducirNumeros1;
    private javax.swing.JTextField txtNumeros;
    private javax.swing.JTextField txtNumeros1;
    public static javax.swing.JTextField txtNumerosOrdenados;
    private javax.swing.JTextField txtNumerosOrdenados1;
    // End of variables declaration//GEN-END:variables


}
