
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usuario
 */
public class DobleV extends javax.swing.JFrame {

    /**
     * Creates new form DobleV
     */
    public DobleV() {
        initComponents();
        modelo=(DefaultTableModel)tblList.getModel();
        ListD=new ListaDoble();
        tblList.getTableHeader().setVisible(false);
        this.setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDat = new javax.swing.JButton();
        txtDato = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblList = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        lblSuma = new javax.swing.JLabel();
        lblMayor = new javax.swing.JLabel();
        lblMenor = new javax.swing.JLabel();
        lblPares = new javax.swing.JLabel();
        lblImpares = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDat.setText("Insertar");
        btnDat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatActionPerformed(evt);
            }
        });

        txtDato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDatoKeyPressed(evt);
            }
        });

        tblList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblList);

        jButton2.setText("Sacar");

        lblSuma.setText("Suma:");

        lblMayor.setText("Mayor:");

        lblMenor.setText("Menor:");

        lblPares.setText("Pares:");

        lblImpares.setText("Impares:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSuma)
                                .addGap(37, 37, 37)
                                .addComponent(lblMayor)
                                .addGap(30, 30, 30)
                                .addComponent(lblMenor)
                                .addGap(35, 35, 35)
                                .addComponent(lblPares)
                                .addGap(37, 37, 37)
                                .addComponent(lblImpares)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDato, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnDat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDat)
                    .addComponent(txtDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSuma)
                    .addComponent(lblMayor)
                    .addComponent(lblMenor)
                    .addComponent(lblPares)
                    .addComponent(lblImpares))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void tam(){
    try{
        modelo.setColumnCount(ListD.lengthList()+1);
        modelo.setRowCount(3);
    }
    
    catch(NumberFormatException e){
        javax.swing.JOptionPane.showMessageDialog(this,e.getMessage());
    }catch(ArrayIndexOutOfBoundsException e){}
    }//para el tamaño
    private void limpiarTbl(){
        for(int i=0;i<ListD.lengthList();i++){
            modelo.setValueAt("", 0, 0);
                modelo.setValueAt("", 1, i);
                modelo.setValueAt("", 2, i);
                        

                
        }
    }
    
    
    private void llenarTblV3(){
        //i<=getfin
        
        for(int i=0;i<ListD.lengthList();i++){
            try {
                modelo.setValueAt("Null", 1, 0);
                modelo.setValueAt("Primero", 0, 0);
                modelo.setValueAt("|"+ListD.getPos(i)+"|====", 1, i);
                modelo.setValueAt("Ultimo", 2, ListD.lengthList()-1);
                modelo.setValueAt("Null", 1, ListD.lengthList());

                  } catch (Exception ex) {
                Logger.getLogger(DobleV.class.getName()).log(Level.SEVERE, null, ex);
            }

            
        }
                        tblList.getColumnModel().getColumn(0).setWidth(1000);

    }
    private void btnDatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatActionPerformed
        try{
            //Racional dato;
            //dato = new Racional("2/3");
            //ListD.agregar(dato);
            ListD.agregar(new Racional(txtDato.getText()));
            tam();
            limpiarTbl();
            //llenarTbl();
            llenarTblV3();
            txtDato.setText("");
            lblSuma.setText("Suma: "+ListD.Suma());
            lblMayor.setText("Mayor: "+ListD.mayor());
            lblMenor.setText("Menor: "+ListD.menor());
            lblPares.setText("Pares: "+ListD.pares());
            lblImpares.setText("Impares: "+ListD.inpares());
        }
        catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(this,e.getMessage());}
        // TODO add your handling code here:
         
                // TODO add your handling code here:
    }//GEN-LAST:event_btnDatActionPerformed

    private void txtDatoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatoKeyPressed
       char tecla=evt.getKeyChar();
       if(tecla==KeyEvent.VK_ENTER){
         btnDat.doClick();
       }
    }//GEN-LAST:event_txtDatoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DobleV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DobleV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DobleV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DobleV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DobleV().setVisible(true);
            }
        });
    }
    public DefaultTableModel modelo;
    public ListaDoble ListD;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDat;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImpares;
    private javax.swing.JLabel lblMayor;
    private javax.swing.JLabel lblMenor;
    private javax.swing.JLabel lblPares;
    private javax.swing.JLabel lblSuma;
    private javax.swing.JTable tblList;
    private javax.swing.JTextField txtDato;
    // End of variables declaration//GEN-END:variables
}
