
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author BrandonUlises
 */
public class Gui extends javax.swing.JFrame {

    /**
     * Creates new form Gui
     */
    public Gui() {    
        initComponents();
        modelo=(DefaultTableModel)tblTitulos.getModel();
        this.setLocationRelativeTo(null);
        //PanelNots.setVisible(false);
        PanelUser.setVisible(true);
        tblTitulos.getTableHeader().setVisible(false);
        // PanelDats.setVisible(false);
        //modelo.setValueAt("Primero", 0, 0);
        ListDC=new ListaDobleCircular();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        PanelDats = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTitulos = new javax.swing.JTable();
        lbNueva = new javax.swing.JLabel();
        lbEliminar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PanelUser = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtUsuario1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNots = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        PanelFondo.setBackground(new java.awt.Color(0, 102, 204));
        PanelFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        PanelDats.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setAlignmentY(2.0F);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("NOTE PAD");

        tblTitulos= new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex){
                return false;
            }

        };
        tblTitulos.setBackground(new java.awt.Color(204, 204, 204));
        tblTitulos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tblTitulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1"
            }
        ));
        tblTitulos.setRowHeight(20);
        tblTitulos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblTitulosFocusGained(evt);
            }
        });
        tblTitulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTitulosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTitulos);

        lbNueva.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbNueva.setText("+");
        lbNueva.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lbNuevaMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbNuevaMouseMoved(evt);
            }
        });
        lbNueva.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lbNuevaFocusGained(evt);
            }
        });
        lbNueva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbNuevaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbNuevaMouseExited(evt);
            }
        });

        lbEliminar.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lbEliminar.setText("-");
        lbEliminar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lbEliminarMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbEliminarMouseMoved(evt);
            }
        });
        lbEliminar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lbEliminarFocusGained(evt);
            }
        });
        lbEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbEliminarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbEliminarMouseExited(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\DigitalMonster\\Downloads\\11111.png")); // NOI18N

        javax.swing.GroupLayout PanelDatsLayout = new javax.swing.GroupLayout(PanelDats);
        PanelDats.setLayout(PanelDatsLayout);
        PanelDatsLayout.setHorizontalGroup(
            PanelDatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(PanelDatsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(PanelDatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNueva, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(75, 75, 75))
            .addGroup(PanelDatsLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelDatsLayout.setVerticalGroup(
            PanelDatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDatsLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDatsLayout.createSequentialGroup()
                        .addComponent(lbNueva)
                        .addGap(18, 18, 18)
                        .addComponent(lbEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PanelUser.setBackground(new java.awt.Color(255, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/585e4be1cb11b227491c3398-i.png"))); // NOI18N

        txtUsuario.setBackground(new java.awt.Color(0, 39, 255));
        txtUsuario.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        txtUsuario.setText("Usuario");
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        txtUsuario1.setBackground(new java.awt.Color(0, 39, 255));
        txtUsuario1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        txtUsuario1.setText("Contraseña");
        txtUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuario1ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1000px-Circle_arrow_right_font_awesome.svg-iloveimg-resized.png"))); // NOI18N

        javax.swing.GroupLayout PanelUserLayout = new javax.swing.GroupLayout(PanelUser);
        PanelUser.setLayout(PanelUserLayout);
        PanelUserLayout.setHorizontalGroup(
            PanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUserLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(195, 195, 195))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUserLayout.createSequentialGroup()
                        .addGroup(PanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUserLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(163, 163, 163))))
        );
        PanelUserLayout.setVerticalGroup(
            PanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUserLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(txtUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtNots.setColumns(20);
        txtNots.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtNots.setRows(5);
        jScrollPane2.setViewportView(txtNots);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\DigitalMonster\\Downloads\\save.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelFondoLayout = new javax.swing.GroupLayout(PanelFondo);
        PanelFondo.setLayout(PanelFondoLayout);
        PanelFondoLayout.setHorizontalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addComponent(PanelDats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFondoLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(597, 597, 597)
                        .addComponent(PanelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(778, 778, 778)
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFondoLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelFondoLayout.setVerticalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(PanelFondoLayout.createSequentialGroup()
                        .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelFondoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2))
                    .addComponent(PanelDats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelFondoLayout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(496, 496, 496)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 1061, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void llenarTblV3(){
        //i<=getfin
        
        for(int i=0;i<ListDC.lengthList();i++){
            try {
                modelo.setValueAt(ListDC.getPos(i), i, 0);
               // modelo.setValueAt("|"+ListDC.getPos(i)+"|====", 1, i);
               // modelo.setValueAt("Ultimo", 2, ListDC.lengthList()-1);
               // modelo.setValueAt("Null", 1, ListDC.lengthList());

                // modelo.setValueAt("Final", 1, cc.getFinal());
                // modelo.setValueAt("Frente", 2, cc.getFrente());
            } catch (Exception ex) {
            }

            
        }
                        tblTitulos.getColumnModel().getColumn(0).setWidth(1000);

    }
    private void tam(){
    try{
        //modelo.setColumnCount(ListDC.lengthList()+1);
        modelo.setRowCount(ListDC.lengthList());
    }
    
    catch(NumberFormatException e){
        javax.swing.JOptionPane.showMessageDialog(this,e.getMessage());
    }catch(ArrayIndexOutOfBoundsException e){}
    }//para el tamaño


   private void limpiarTbl(){
        for(int i=0;i<ListDC.lengthList();i++){
            modelo.setValueAt("", i, 0);
           
        }
    }//LimpiarTabla


    
    private void txtUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuario1ActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void lbNuevaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNuevaMouseExited
        // lbNueva.setText("+");
        lbNueva.setForeground(Color.BLACK);
    }//GEN-LAST:event_lbNuevaMouseExited

    private void lbNuevaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lbNuevaFocusGained

        // TODO add your handling code here:
    }//GEN-LAST:event_lbNuevaFocusGained

    private void lbNuevaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNuevaMouseMoved
        // lbNueva.setText("hola");
        lbNueva.setForeground(Color.red);
        // TODO add your handling code here:
    }//GEN-LAST:event_lbNuevaMouseMoved

    private void lbNuevaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNuevaMouseDragged
        // lbNueva.setText("+");

        // TODO add your handling code here:
    }//GEN-LAST:event_lbNuevaMouseDragged

    private void lbNuevaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNuevaMouseClicked
      
        
      Titulo= javax.swing.JOptionPane.showInputDialog("Titulo");
      ListDC.agregar(new Alumnos(Titulo));
      System.out.println(Titulo);
      tam();
      llenarTblV3();
      txtNots.requestFocus();

        // TODO add your handling code here:
    }//GEN-LAST:event_lbNuevaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       // String dato=String.valueOf(modelo.getValueAt(tblTitulos.getSelectedRow(),0));
       // txtNots.getText();
       ListDC.modificarNota(Titulo,txtNots.getText()); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblTitulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTitulosMouseClicked

        txtNots.setText("Seleccionar titulo");
       String dato=String.valueOf(modelo.getValueAt(tblTitulos.getSelectedRow(),0));
       Titulo=dato;
       System.out.print(ListDC.buscarTx(Titulo));
       txtNots.setText(ListDC.buscarTx(Titulo));
       
        
// TODO add your handling code here:
    }//GEN-LAST:event_tblTitulosMouseClicked

    private void tblTitulosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblTitulosFocusGained
        /*
        txtNots.setText("selected");
       String dato=String.valueOf(modelo.getValueAt(tblTitulos.getSelectedRow(),0));
       Titulo=dato;
       System.out.print(ListDC.buscarTx(Titulo));
       txtNots.setText(ListDC.buscarTx(Titulo));
        */
    }//GEN-LAST:event_tblTitulosFocusGained

    private void lbEliminarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEliminarMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_lbEliminarMouseDragged

    private void lbEliminarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEliminarMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_lbEliminarMouseMoved

    private void lbEliminarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lbEliminarFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_lbEliminarFocusGained

    private void lbEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEliminarMouseClicked
 String dato=String.valueOf(modelo.getValueAt(tblTitulos.getSelectedRow(),0));
      ListDC.menosAmigos(dato);
      limpiarTbl();
      System.out.println(Titulo);
      tam();
      llenarTblV3();
      txtNots.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_lbEliminarMouseClicked

    private void lbEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEliminarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lbEliminarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }
    public DefaultTableModel modelo;
    public ListaDobleCircular ListDC;
    public String Titulo;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDats;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JPanel PanelUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbEliminar;
    private javax.swing.JLabel lbNueva;
    private javax.swing.JTable tblTitulos;
    private javax.swing.JTextArea txtNots;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtUsuario1;
    // End of variables declaration//GEN-END:variables
}
